name: goals-caching
description: This is an action cache open-sauced-goals to data.json
author: Brian Douglas
branding:
  icon: 'thumbs-up'
  color: 'white'

runs:
  using: "composite"
  steps:
  - run: node action.mjs
