name: goals-caching
description: This is an action cache open-sauced-goals to data.json
author: Brian Douglas
branding:
  icon: 'thumbs-up'
  color: 'white'

runs:
  using: "composite"
  steps:
    - run: |
        curl 'https://serve.onegraph.com/graphql?app_id=306cccd5-09ba-4d57-8c76-a3b3af68c36e' \
        --compressed \
        -X POST \
        -H "Content-Type: application/json" \
        -H "Accept: application/json" \
        -H "Accept-Encoding: gzip, deflate" \
        -vv \
        --data "{
          \"query\": \"query ViewerOpenSaucedGoalsAndStarredRepos(\$gitHubOAuthToken: String!) { gitHub(auths: {gitHubOAuthToken: \$gitHubOAuthToken}) { viewer { starredRepositories(first: 10, orderBy: {field: STARRED_AT, direction: DESC}) { totalCount edges { node { nameWithOwner } } } repository(name: \\\"open-sauced-goals\\\") { issues(first: 10, orderBy: {field: CREATED_AT, direction: DESC}) { edges { node { title } } } } } } }\",
          \"variables\": {\"gitHubOAuthToken\": \"$GITHUB_TOKEN\"},
          \"operationName\": \"ViewerOpenSaucedGoalsAndStarredRepos\"
      shell: bash
    - run: |
        git config user.name GitHub
        git config user.email noreply@github.com
        git remote set-url origin https://x-access-token:${{ GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      shell: bash
    - run: |
        git add .
        if output=$(git status --porcelain) && [ ! -z "$output" ]; then
          git commit --author "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>" --message "update the goals cache"
          git push
        fi
      shell: bash
